#coding=utf-8
#import libs 
import sys
import Page1_cmd
import Page1_sty
import Fun
import os
import TabPage1
import tkinter
from   tkinter import *
import tkinter.ttk
import tkinter.font
#Add your Varial Here: (Keep This Line of comments)
#Define UI Class
class  Page1:
    def __init__(self,root,isTKroot = True):
        uiName = self.__class__.__name__
        Fun.Register(uiName,'UIClass',self)
        self.root = root
        Fun.Register(uiName,'root',root)
        style = Page1_sty.SetupStyle()
        if isTKroot == True:
            root.title("None")
            if os.path.exists("D:\TKinterDesigner-master\Ico\Curve.png"):
                root.iconbitmap("D:\TKinterDesigner-master\Ico\Curve.png")
            Fun.CenterDlg(uiName,root,891,607)
            root['background'] = '#efefef'
        Form_1= tkinter.Canvas(root,width = 10,height = 4)
        Form_1.place(x = 0,y = 0,width = 891,height = 607)
        Form_1.configure(bg = "#efefef")
        Form_1.configure(highlightthickness = 0)
        Fun.Register(uiName,'Form_1',Form_1)
        Group_1_Variable = Fun.AddTKVariable(uiName,'Group_1')
        Group_1_Variable.set(1)
        #Create the elements of root 
        Label_2 = tkinter.Label(Form_1,text="起始日期")
        Fun.Register(uiName,'Label_2',Label_2)
        Fun.SetControlPlace(uiName,'Label_2',62,141,82,20)
        Label_2.configure(relief = "flat")
        Label_4 = tkinter.Label(Form_1,text="注册地")
        Fun.Register(uiName,'Label_4',Label_4)
        Fun.SetControlPlace(uiName,'Label_4',66,194,82,20)
        Label_4.configure(relief = "flat")
        Label_7 = tkinter.Label(Form_1,text="截至日期")
        Fun.Register(uiName,'Label_7',Label_7)
        Fun.SetControlPlace(uiName,'Label_7',284,141,82,20)
        Label_7.configure(relief = "flat")
        Entry_8_Variable = Fun.AddTKVariable(uiName,'Entry_8','')
        Entry_8 = tkinter.Entry(Form_1,textvariable=Entry_8_Variable)
        Fun.Register(uiName,'Entry_8',Entry_8)
        Fun.SetControlPlace(uiName,'Entry_8',361,141,131,20)
        Entry_8.configure(relief = "sunken")
        Label_9 = tkinter.Label(Form_1,text="查询内容")
        Fun.Register(uiName,'Label_9',Label_9)
        Fun.SetControlPlace(uiName,'Label_9',66,234,82,20)
        Label_9.configure(relief = "flat")
        Button_11 = tkinter.Button(Form_1,text="查询")
        Fun.Register(uiName,'Button_11',Button_11,'Button_querry')
        Fun.SetControlPlace(uiName,'Button_11',218,274,100,28)
        Button_11.configure(command=lambda:Page1_cmd.Button_11_onCommand(uiName,"Button_11"))
        ComboBox_13_Variable = Fun.AddTKVariable(uiName,'ComboBox_13')
        ComboBox_13 = tkinter.ttk.Combobox(Form_1,textvariable=ComboBox_13_Variable, state="readonly")
        Fun.Register(uiName,'ComboBox_13',ComboBox_13)
        Fun.SetControlPlace(uiName,'ComboBox_13',151,194,100,20)
        ComboBox_13.configure(state = "readonly")
        ComboBox_13["values"]=['全部','海口','洋浦']
        ComboBox_13.current(0)
        ComboBox_14_Variable = Fun.AddTKVariable(uiName,'ComboBox_14')
        ComboBox_14 = tkinter.ttk.Combobox(Form_1,textvariable=ComboBox_14_Variable, state="readonly")
        Fun.Register(uiName,'ComboBox_14',ComboBox_14)
        Fun.SetControlPlace(uiName,'ComboBox_14',151,234,100,20)
        ComboBox_14.configure(state = "readonly")
        ComboBox_14["values"]=['所有','开票额','纳税额','返税额-所有','返税额-应返','返税额-实返']
        ComboBox_14.current(0)
        Label_15 = tkinter.Label(Form_1,text="查询方式")
        Fun.Register(uiName,'Label_15',Label_15)
        Fun.SetControlPlace(uiName,'Label_15',266,234,100,20)
        Label_15.configure(relief = "flat")
        ComboBox_18_Variable = Fun.AddTKVariable(uiName,'ComboBox_18')
        ComboBox_18 = tkinter.ttk.Combobox(Form_1,textvariable=ComboBox_18_Variable, state="readonly")
        Fun.Register(uiName,'ComboBox_18',ComboBox_18)
        Fun.SetControlPlace(uiName,'ComboBox_18',358,234,131,20)
        ComboBox_18.configure(state = "readonly")
        ComboBox_18["values"]=['每个月总和','每个公司总和']
        ComboBox_18.current(0)
        Button_21 = tkinter.Button(Form_1,text="下载最新数据")
        Fun.Register(uiName,'Button_21',Button_21,'Button_download')
        Fun.SetControlPlace(uiName,'Button_21',631,137,100,28)
        Button_21.configure(command=lambda:Page1_cmd.Button_21_onCommand(uiName,"Button_21"))
        Label_26 = tkinter.Label(Form_1,text="运行日志")
        Fun.Register(uiName,'Label_26',Label_26)
        Fun.SetControlPlace(uiName,'Label_26',30,324,100,20)
        Label_26.configure(relief = "flat")
        Button_27 = tkinter.Button(Form_1,text="匹配结果")
        Fun.Register(uiName,'Button_27',Button_27,'Button_match')
        Fun.SetControlPlace(uiName,'Button_27',631,282,100,28)
        Button_27.configure(command=lambda:Page1_cmd.Button_27_onCommand(uiName,"Button_27"))
        Button_28 = tkinter.Button(Form_1,text="撰写经济分析报告")
        Fun.Register(uiName,'Button_28',Button_28,'Button_report1')
        Fun.SetControlPlace(uiName,'Button_28',747,182,100,28)
        Button_28.configure(command=lambda:Page1_cmd.Button_28_onCommand(uiName,"Button_28"))
        Button_29 = tkinter.Button(Form_1,text="会员分析报告")
        Fun.Register(uiName,'Button_29',Button_29,'Button_report2')
        Fun.SetControlPlace(uiName,'Button_29',631,234,100,28)
        Button_29.configure(command=lambda:Page1_cmd.Button_29_onCommand(uiName,"Button_29"))
        Label_30 = tkinter.Label(Form_1,text="交易中心数据分析系统")
        Fun.Register(uiName,'Label_30',Label_30)
        Fun.SetControlPlace(uiName,'Label_30',189,43,501,42)
        Label_30.configure(relief = "flat")
        Label_30_Ft=tkinter.font.Font(family='楷体', size=27,weight='bold',slant='italic',underline=0,overstrike=0)
        Label_30.configure(font = Label_30_Ft)
        Label_31 = tkinter.Label(Form_1,text="例：202201")
        Fun.Register(uiName,'Label_31',Label_31)
        Fun.SetControlPlace(uiName,'Label_31',127,113,100,20)
        Label_31.configure(relief = "flat")
        Label_32 = tkinter.Label(Form_1,text="是否剔除不返税的四家企业")
        Fun.Register(uiName,'Label_32',Label_32)
        Fun.SetControlPlace(uiName,'Label_32',280,194,164,20)
        Label_32.configure(relief = "flat")
        ComboBox_34_Variable = Fun.AddTKVariable(uiName,'ComboBox_34')
        ComboBox_34 = tkinter.ttk.Combobox(Form_1,textvariable=ComboBox_34_Variable, state="readonly")
        Fun.Register(uiName,'ComboBox_34',ComboBox_34)
        Fun.SetControlPlace(uiName,'ComboBox_34',451,194,100,20)
        ComboBox_34.configure(state = "readonly")
        ComboBox_34["values"]=['否','是']
        ComboBox_34.current(0)
        Button_35 = tkinter.Button(Form_1,text="异常数据检测")
        Fun.Register(uiName,'Button_35',Button_35,'Button_error')
        Fun.SetControlPlace(uiName,'Button_35',747,234,100,28)
        Button_36 = tkinter.Button(Form_1,text="导出完税证明")
        Fun.Register(uiName,'Button_36',Button_36,'Button_Reload')
        Fun.SetControlPlace(uiName,'Button_36',747,133,100,28)
        Button_36.configure(command=lambda:Page1_cmd.Button_36_onCommand(uiName,"Button_36"))
        Button_37 = tkinter.Button(Form_1,text="开票类型统计")
        Fun.Register(uiName,'Button_37',Button_37,'Button_goods')
        Fun.SetControlPlace(uiName,'Button_37',631,182,100,28)
        Button_37.configure(command=lambda:Page1_cmd.Button_37_onCommand(uiName,"Button_37"))
        ListBox_43 = tkinter.Listbox(Form_1)
        Fun.Register(uiName,'ListBox_43',ListBox_43)
        Fun.SetControlPlace(uiName,'ListBox_43',100,352,473,174)
        ListBox_43.configure(selectmode = "multiple")
        ListBox_43_Scrollbar = tkinter.Scrollbar(ListBox_43,orient=tkinter.VERTICAL)
        ListBox_43_Scrollbar.place(x = 453,y = 0,width = 20,height = 174)
        ListBox_43_Scrollbar.config(command = ListBox_43.yview)
        ListBox_43.config(yscrollcommand = ListBox_43_Scrollbar.set)
        Entry_39_Variable = Fun.AddTKVariable(uiName,'Entry_39','')
        Entry_39 = tkinter.Entry(Form_1,textvariable=Entry_39_Variable)
        Fun.Register(uiName,'Entry_39',Entry_39)
        Fun.SetControlPlace(uiName,'Entry_39',153,141,127,20)
        Entry_39.configure(relief = "sunken")
        Frame_69 = tkinter.Frame(Form_1)
        Fun.Register(uiName,'Frame_69',Frame_69)
        Fun.SetControlPlace(uiName,'Frame_69',690,381,125,25)
        Frame_69.configure(bg = "#888888")
        Frame_69.configure(relief = "sunken")
        TabPage1_69 = TabPage1.TabPage1(Frame_69,False)
        Fun.Register(uiName,'TabPage1_69',TabPage1_69)
        Button_70 = tkinter.Button(Form_1,text="企业查询")
        Fun.Register(uiName,'Button_70',Button_70)
        Fun.SetControlPlace(uiName,'Button_70',747,282,100,28)
        Button_70.configure(command=lambda:Page1_cmd.Button_70_onCommand(uiName,"Button_70"))
        #Inital all element's Data 
        Fun.InitElementData(uiName)
        #Add Some Logic Code Here: (Keep This Line of comments)


#Create the root of Kinter 
if  __name__ == '__main__':
    root = tkinter.Tk()
    MyDlg = Page1(root)
    root.mainloop()
